# docker-compose -f docker-compose.yml -f docker-compose.obs.yml up -d

services:
  
  # Observability
  # back-ends
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # WebApp, what you can access in your browser
      - "14250" # For communication

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger
