name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '5.0'
    - name: Find sln
      run: cd AJProds.EFDataSeeder
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet run --project AJProds.EFDataSeeder
