name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./AJProds.EFDataSeeder
    steps:
    - uses: actions/checkout@v2.4.0
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '5.0'
    
    - name: Install dependencies
      run: dotnet restore AJProds.EFDataSeeder.sln
    
    - name: Build
      run: dotnet build --configuration Release --no-restore AJProds.EFDataSeeder.sln
    
    - name: Test
      run: dotnet test -c Release --no-build --no-restore AJProds.EFDataSeeder.sln
